<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * TMDB production companies. Their absence was only noticed when the film-guessing game
 * needed a clue between "pays de production" and "réalisateur·rice"; existing rows are
 * filled in by app:tmdb:backfill-studios rather than by a re-enrichment, which would
 * rewrite every other field too.
 */
final class Version20260826185645 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute les studios (production companies TMDB) et leur liaison aux films.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE movie_studio (movie_id INT NOT NULL, studio_id INT NOT NULL, PRIMARY KEY (movie_id, studio_id))');
        $this->addSql('CREATE INDEX IDX_B3EC9AC38F93B6FC ON movie_studio (movie_id)');
        $this->addSql('CREATE INDEX IDX_B3EC9AC3446F285F ON movie_studio (studio_id)');
        $this->addSql('CREATE TABLE studio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT NOT NULL, name VARCHAR(200) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_studio_tmdb_id ON studio (tmdb_id)');
        $this->addSql('ALTER TABLE movie_studio ADD CONSTRAINT FK_B3EC9AC38F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE movie_studio ADD CONSTRAINT FK_B3EC9AC3446F285F FOREIGN KEY (studio_id) REFERENCES studio (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE movie_studio DROP CONSTRAINT FK_B3EC9AC38F93B6FC');
        $this->addSql('ALTER TABLE movie_studio DROP CONSTRAINT FK_B3EC9AC3446F285F');
        $this->addSql('DROP TABLE movie_studio');
        $this->addSql('DROP TABLE studio');
    }
}
