<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The "guess the film" game board. The answer is a column here rather than client state:
 * it must stay on the server until the run is over, and the daily mode needs a row to make
 * "one puzzle a day" enforceable.
 */
final class Version20260826170623 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute la table game_session (jeu "devine le film", modes quotidien et infini).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE game_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mode VARCHAR(20) NOT NULL, puzzle_date DATE DEFAULT NULL, guesses JSON NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, movie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4586AAFBA76ED395 ON game_session (user_id)');
        $this->addSql('CREATE INDEX IDX_4586AAFB8F93B6FC ON game_session (movie_id)');
        $this->addSql('CREATE INDEX idx_game_session_user_mode_status ON game_session (user_id, mode, status)');
        // puzzle_date is null for infinite runs and Postgres lets nulls repeat, so this
        // only ever constrains the daily mode.
        $this->addSql('CREATE UNIQUE INDEX uniq_game_session_daily ON game_session (user_id, mode, puzzle_date)');
        $this->addSql('ALTER TABLE game_session ADD CONSTRAINT FK_4586AAFBA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_session ADD CONSTRAINT FK_4586AAFB8F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE game_session DROP CONSTRAINT FK_4586AAFBA76ED395');
        $this->addSql('ALTER TABLE game_session DROP CONSTRAINT FK_4586AAFB8F93B6FC');
        $this->addSql('DROP TABLE game_session');
    }
}
