<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260822142253 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema: movies, people/credits, genres/countries, watches, tags, watchlist, import tracking.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE country (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, iso_code VARCHAR(2) NOT NULL, name VARCHAR(150) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_country_iso_code ON country (iso_code)');
        $this->addSql('CREATE TABLE credit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) NOT NULL, character_name VARCHAR(255) DEFAULT NULL, cast_order INT DEFAULT NULL, movie_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1CC16EFE8F93B6FC ON credit (movie_id)');
        $this->addSql('CREATE INDEX IDX_1CC16EFE217BBB47 ON credit (person_id)');
        $this->addSql('CREATE INDEX idx_credit_role ON credit (role)');
        $this->addSql('CREATE UNIQUE INDEX uniq_credit_movie_person_role_character ON credit (movie_id, person_id, role, character_name)');
        $this->addSql('CREATE TABLE genre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_genre_tmdb_id ON genre (tmdb_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_genre_name ON genre (name)');
        $this->addSql('CREATE TABLE import_batch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filename VARCHAR(255) NOT NULL, file_type VARCHAR(20) NOT NULL, status VARCHAR(30) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, rows_total INT NOT NULL, rows_imported INT NOT NULL, rows_skipped INT NOT NULL, rows_failed INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE import_row_error (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, row_number INT NOT NULL, raw_data JSON NOT NULL, error_message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, import_batch_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_23BEE6BD5A310080 ON import_row_error (import_batch_id)');
        $this->addSql('CREATE TABLE movie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT DEFAULT NULL, imdb_id VARCHAR(20) DEFAULT NULL, letterboxd_slug VARCHAR(255) NOT NULL, title VARCHAR(500) NOT NULL, original_title VARCHAR(500) DEFAULT NULL, release_date DATE DEFAULT NULL, release_year INT DEFAULT NULL, runtime_minutes INT DEFAULT NULL, synopsis TEXT DEFAULT NULL, tagline VARCHAR(500) DEFAULT NULL, original_language VARCHAR(10) DEFAULT NULL, budget BIGINT DEFAULT NULL, revenue BIGINT DEFAULT NULL, popularity DOUBLE PRECISION DEFAULT NULL, tmdb_vote_average DOUBLE PRECISION DEFAULT NULL, tmdb_vote_count INT DEFAULT NULL, poster_path VARCHAR(255) DEFAULT NULL, backdrop_path VARCHAR(255) DEFAULT NULL, enrichment_status VARCHAR(20) NOT NULL, enrichment_error TEXT DEFAULT NULL, last_enrichment_attempt_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_movie_enrichment_status ON movie (enrichment_status)');
        $this->addSql('CREATE UNIQUE INDEX uniq_movie_letterboxd_slug ON movie (letterboxd_slug)');
        $this->addSql('CREATE UNIQUE INDEX uniq_movie_tmdb_id ON movie (tmdb_id)');
        $this->addSql('CREATE TABLE movie_genre (movie_id INT NOT NULL, genre_id INT NOT NULL, PRIMARY KEY (movie_id, genre_id))');
        $this->addSql('CREATE INDEX IDX_FD1229648F93B6FC ON movie_genre (movie_id)');
        $this->addSql('CREATE INDEX IDX_FD1229644296D31F ON movie_genre (genre_id)');
        $this->addSql('CREATE TABLE movie_country (movie_id INT NOT NULL, country_id INT NOT NULL, PRIMARY KEY (movie_id, country_id))');
        $this->addSql('CREATE INDEX IDX_73E58B488F93B6FC ON movie_country (movie_id)');
        $this->addSql('CREATE INDEX IDX_73E58B48F92F3E70 ON movie_country (country_id)');
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, profile_path VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_person_tmdb_id ON person (tmdb_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tag_name ON tag (name)');
        $this->addSql('CREATE TABLE watch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, watched_date DATE DEFAULT NULL, rating NUMERIC(2, 1) DEFAULT NULL, is_rewatch BOOLEAN NOT NULL, review_text TEXT DEFAULT NULL, contains_spoilers BOOLEAN NOT NULL, source VARCHAR(20) NOT NULL, external_ref VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, movie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_watch_watched_date ON watch (watched_date)');
        $this->addSql('CREATE INDEX idx_watch_movie ON watch (movie_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_watch_external_ref ON watch (external_ref)');
        $this->addSql('CREATE TABLE watch_tag (watch_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (watch_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_3E29DEB2C7C58135 ON watch_tag (watch_id)');
        $this->addSql('CREATE INDEX IDX_3E29DEB2BAD26311 ON watch_tag (tag_id)');
        $this->addSql('CREATE TABLE watchlist_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, added_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, movie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_watchlist_entry_movie ON watchlist_entry (movie_id)');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE8F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE import_row_error ADD CONSTRAINT FK_23BEE6BD5A310080 FOREIGN KEY (import_batch_id) REFERENCES import_batch (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE movie_genre ADD CONSTRAINT FK_FD1229648F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE movie_genre ADD CONSTRAINT FK_FD1229644296D31F FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE movie_country ADD CONSTRAINT FK_73E58B488F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE movie_country ADD CONSTRAINT FK_73E58B48F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE watch ADD CONSTRAINT FK_500B4A268F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE watch_tag ADD CONSTRAINT FK_3E29DEB2C7C58135 FOREIGN KEY (watch_id) REFERENCES watch (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE watch_tag ADD CONSTRAINT FK_3E29DEB2BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE watchlist_entry ADD CONSTRAINT FK_85F2069C8F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE credit DROP CONSTRAINT FK_1CC16EFE8F93B6FC');
        $this->addSql('ALTER TABLE credit DROP CONSTRAINT FK_1CC16EFE217BBB47');
        $this->addSql('ALTER TABLE import_row_error DROP CONSTRAINT FK_23BEE6BD5A310080');
        $this->addSql('ALTER TABLE movie_genre DROP CONSTRAINT FK_FD1229648F93B6FC');
        $this->addSql('ALTER TABLE movie_genre DROP CONSTRAINT FK_FD1229644296D31F');
        $this->addSql('ALTER TABLE movie_country DROP CONSTRAINT FK_73E58B488F93B6FC');
        $this->addSql('ALTER TABLE movie_country DROP CONSTRAINT FK_73E58B48F92F3E70');
        $this->addSql('ALTER TABLE watch DROP CONSTRAINT FK_500B4A268F93B6FC');
        $this->addSql('ALTER TABLE watch_tag DROP CONSTRAINT FK_3E29DEB2C7C58135');
        $this->addSql('ALTER TABLE watch_tag DROP CONSTRAINT FK_3E29DEB2BAD26311');
        $this->addSql('ALTER TABLE watchlist_entry DROP CONSTRAINT FK_85F2069C8F93B6FC');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE credit');
        $this->addSql('DROP TABLE genre');
        $this->addSql('DROP TABLE import_batch');
        $this->addSql('DROP TABLE import_row_error');
        $this->addSql('DROP TABLE movie');
        $this->addSql('DROP TABLE movie_genre');
        $this->addSql('DROP TABLE movie_country');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE watch');
        $this->addSql('DROP TABLE watch_tag');
        $this->addSql('DROP TABLE watchlist_entry');
    }
}
