<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Turns the single-tenant schema multi-user.
 *
 * Watches, watchlist entries, imports and the Letterboxd sync state all gain an owner. The
 * columns cannot simply be added NOT NULL — existing installs already hold rows — so each
 * one lands nullable, gets backfilled onto an owner account this migration creates, and is
 * only then tightened. That owner is the account the pre-multi-user library belonged to.
 *
 * It is created with a deliberately unusable password: no hasher can ever validate "!", so
 * the row exists to own data but cannot be logged into until UserFixtures (or a manual
 * password reset) sets a real hash. That keeps a hardcoded credential out of the schema
 * history, which is committed and shared.
 *
 * The two unique indexes that assumed a single tenant become composite: two accounts must
 * be able to log the same Letterboxd diary entry, and to watchlist the same film.
 */
final class Version20260825113021 extends AbstractMigration
{
    private const OWNER_EMAIL = 'tom.sikora03@gmail.com';
    private const OWNER_DISPLAY_NAME = 'Tom';
    private const UNUSABLE_PASSWORD = '!';

    public function getDescription(): string
    {
        return 'Introduces user accounts and profile sharing; assigns all pre-existing personal data to the owner account.';
    }

    public function up(Schema $schema): void
    {
        $this->createUserAndSharingTables();
        $this->createOwnerAccount();
        $this->attachExistingDataToOwner();
    }

    private function createUserAndSharingTables(): void
    {
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, display_name VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, letterboxd_username VARCHAR(255) DEFAULT NULL, rss_sync_enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON app_user (email)');

        $this->addSql('CREATE TABLE profile_access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, granted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, viewer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6E434C337E3C61F9 ON profile_access (owner_id)');
        $this->addSql('CREATE INDEX idx_profile_access_viewer ON profile_access (viewer_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_profile_access_pair ON profile_access (owner_id, viewer_id)');
        $this->addSql('ALTER TABLE profile_access ADD CONSTRAINT FK_6E434C337E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE profile_access ADD CONSTRAINT FK_6E434C336C59C752 FOREIGN KEY (viewer_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE profile_share_link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_share_link_token ON profile_share_link (token)');
        $this->addSql('CREATE UNIQUE INDEX uniq_share_link_owner ON profile_share_link (owner_id)');
        $this->addSql('ALTER TABLE profile_share_link ADD CONSTRAINT FK_4C00A3357E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    /**
     * The owner account starts with no Letterboxd feed attached, and that is not an omission.
     *
     * These two columns were seeded here from app-wide environment variables while the RSS
     * settings were still a property of the installation rather than of a person. They stopped
     * being that when the app became multi-user, and the account screen now writes them, so
     * reading anything from the environment here would only reintroduce a value nobody can
     * see from inside the app to explain.
     *
     * Harmless to replay on the databases that ran this with the old seed: they were migrated
     * long ago and this INSERT already yields to its ON CONFLICT. On a fresh install the
     * account simply arrives unconfigured, which is the same state any second account has
     * always started in.
     */
    private function createOwnerAccount(): void
    {
        $this->addSql(
            'INSERT INTO app_user (email, display_name, password, roles, letterboxd_username, rss_sync_enabled, created_at)
             VALUES (:email, :displayName, :password, :roles, NULL, false, NOW())
             ON CONFLICT (email) DO NOTHING',
            [
                'email' => self::OWNER_EMAIL,
                'displayName' => self::OWNER_DISPLAY_NAME,
                'password' => self::UNUSABLE_PASSWORD,
                'roles' => json_encode(['ROLE_USER']),
            ]
        );
    }

    private function attachExistingDataToOwner(): void
    {
        $ownerId = sprintf("(SELECT id FROM app_user WHERE email = '%s')", self::OWNER_EMAIL);

        foreach (['watch', 'watchlist_entry', 'import_batch', 'letterboxd_sync_state'] as $table) {
            // Nullable first, backfill, then NOT NULL: the column cannot be added NOT NULL
            // on a table that already has rows, and these tables do on any existing install.
            $this->addSql("ALTER TABLE {$table} ADD user_id INT DEFAULT NULL");
            $this->addSql("UPDATE {$table} SET user_id = {$ownerId}");
            $this->addSql("ALTER TABLE {$table} ALTER COLUMN user_id SET NOT NULL");
            $this->addSql("ALTER TABLE {$table} ADD CONSTRAINT fk_{$table}_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE");
        }

        $this->addSql('CREATE INDEX idx_watch_user ON watch (user_id)');
        $this->addSql('CREATE INDEX idx_watchlist_entry_user ON watchlist_entry (user_id)');
        $this->addSql('CREATE INDEX IDX_85F2069C8F93B6FC ON watchlist_entry (movie_id)');
        $this->addSql('CREATE INDEX idx_import_batch_user ON import_batch (user_id)');

        // Single-tenant uniqueness becomes per-account uniqueness: two users must be able to
        // log the same diary entry and to watchlist the same film.
        $this->addSql('DROP INDEX uniq_watch_external_ref');
        $this->addSql('CREATE UNIQUE INDEX uniq_watch_user_external_ref ON watch (user_id, external_ref)');
        $this->addSql('DROP INDEX uniq_watchlist_entry_movie');
        $this->addSql('CREATE UNIQUE INDEX uniq_watchlist_entry_user_movie ON watchlist_entry (user_id, movie_id)');
        $this->addSql('DROP INDEX uniq_sync_state_username');
        $this->addSql('CREATE UNIQUE INDEX uniq_sync_state_user ON letterboxd_sync_state (user_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX uniq_sync_state_user');
        $this->addSql('CREATE UNIQUE INDEX uniq_sync_state_username ON letterboxd_sync_state (username)');
        $this->addSql('DROP INDEX uniq_watchlist_entry_user_movie');
        $this->addSql('CREATE UNIQUE INDEX uniq_watchlist_entry_movie ON watchlist_entry (movie_id)');
        $this->addSql('DROP INDEX uniq_watch_user_external_ref');
        $this->addSql('CREATE UNIQUE INDEX uniq_watch_external_ref ON watch (external_ref)');

        $this->addSql('DROP INDEX idx_import_batch_user');
        $this->addSql('DROP INDEX IDX_85F2069C8F93B6FC');
        $this->addSql('DROP INDEX idx_watchlist_entry_user');
        $this->addSql('DROP INDEX idx_watch_user');

        foreach (['watch', 'watchlist_entry', 'import_batch', 'letterboxd_sync_state'] as $table) {
            $this->addSql("ALTER TABLE {$table} DROP CONSTRAINT fk_{$table}_user");
            $this->addSql("ALTER TABLE {$table} DROP user_id");
        }

        $this->addSql('ALTER TABLE profile_access DROP CONSTRAINT FK_6E434C337E3C61F9');
        $this->addSql('ALTER TABLE profile_access DROP CONSTRAINT FK_6E434C336C59C752');
        $this->addSql('ALTER TABLE profile_share_link DROP CONSTRAINT FK_4C00A3357E3C61F9');
        $this->addSql('DROP TABLE profile_access');
        $this->addSql('DROP TABLE profile_share_link');
        $this->addSql('DROP TABLE app_user');
    }
}
