<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260823105346 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add letterboxd_sync_state to track RSS sync runs (last run time, status, error).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE letterboxd_sync_state (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              username VARCHAR(255) NOT NULL,
              last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              last_sync_status VARCHAR(20) DEFAULT NULL,
              last_sync_error TEXT DEFAULT NULL,
              last_run_watches_imported INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_sync_state_username ON letterboxd_sync_state (username)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE letterboxd_sync_state');
    }
}
